---
os: linux
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'SIMPLECOV=yes bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.7
stages:
  - static
  - spec
  - acceptance
jobs:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.7
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0.0" RSAPI_GEM_VERSION="~> 1.6.0" CHECK=parallel_spec
      rvm: 2.5.1
      stage: spec
branches:
  only:
    - main
    - /^v\d/
    - release
notifications:
  email: false
  slack:
    secure: Ji4nLIovqAUuTlIHod1ZA+mklXY/qVjRBemMMnP0IttXhzNFqQVk/LsPJbydGxVi5lewace/98v6gcqkfaO03LPP3bKGTbqfDCzTQbzHGq+FISwI4EeyB0dgNT7OQHgTVZxo3PpH0ULWXPjcIwhv9+3cCN37m5MWfbCIfv8sMDpWjjKnQln/Ff+Cz7oVyPMyV7EBnmra2IcurWSoItSm99suwR8R2ERB6mIp2UnscZJ3cSmrS6KDS4BlLdKVqaMbXZw7p3/Kv3MaaNuH7do//1ohTjEe5EmPh8GSCyttJprfUF6896v3mE92A74z0eLLiE561X8g6zdXZ5Ol+s78Sfk+Lwo8sCqxg17BR97zyGr8oJH+wxSeA+MauQinE+YyLbUfc3BE/mgfmYStNNzekqJ1aTqRFC/3YOHYsQ8S/0eTUgXZ/1pu+QwfKGeXTL4Fk1vl8j2IMdXcRvbTMNAWTyunYdOXY1Wo/GXpcAlQQ88N1eNLUxI3qFYLp3Pqlvvr8ypZEEyUMxq7m2upwX4VgzAGbiJZo5r4MqYgWu7f5BMKYikBOgmAkU/YhD4z6eKpLJVyqznZCKziexTltRX8H9Q1fAxS9Xe5c3GZzsSZ46gNn3jADMMStZyugMgl1BnRATAVizovT4OZUS+EDHBfu3XsNsIaLIVuGo3xxfmugS0=
